all:
	g++ -ISDL/include -Iinclude -LSDL/lib -o main *.cpp src/*cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image

# "-mwindows" -  prevents cmd window from opening while running main.exe
# "*.cpp" - compile all cpp files in directory